version: "3"

services:

  influxdb:
    image: influxdb
    volumes:
      - metrics:/var/lib/influxdb
    restart: always

  timescaledb:
    image: timescale/timescaledb
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  skeetereater:
    image: skeetereater
    build:
      context: skeetereater
    environment:
      SKEETER_DB_HOST: timescaledb
      SKEETER_DB_USER: postgres
      SKEETER_DB_PASS: "$POSTGRES_PASSWORD"
      SKEETER_DB_NAME: sensors
      SKEETER_MQTT_HOST: mosquitto
      SKEETER_TOPICS: sensor/+/+
    depends_on:
      - timescaledb
      - mosquitto
    restart: always

  telegraf:
    image: telegraf
    network_mode: service:influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    restart: always

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: always

  grafana:
    image: grafana/grafana
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: always

volumes:
  metrics:
  grafana:
  postgres:
