version: "3"

services:

  timescaledb:
    image: timescale/timescaledb
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  skeetereater:
    image: skeetereater
    build:
      context: skeetereater
    environment:
      SKEETER_DB_HOST: "timescaledb"
      SKEETER_DB_USER: "postgres"
      SKEETER_DB_PASS: "$POSTGRES_PASSWORD"
      SKEETER_DB_NAME: "sensors"
      SKEETER_MQTT_HOST: "mosquitto"
      SKEETER_TOPICS: "sensor/+/+"
      SKEETER_TABLE_NAME_FORMAT: "sensor_{sensor_type}"
      SKEETER_TAG_KEYS: location,topic,sensor_id,sensor_type
    depends_on:
      - timescaledb
      - mosquitto
    restart: always

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    restart: always

  grafana:
    image: grafana/grafana
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: always

  collectd:
    image: collectd
    build:
      context: ./collectd
    ports:
      - "25826:25826/udp"
    environment:
      COLLECTD_HOSTNAME: collectd
      COLLECTD_DB_HOST: "timescaledb"
      COLLECTD_DB_USER: "postgres"
      COLLECTD_DB_PASS: "$POSTGRES_PASSWORD"
      COLLECTD_DB_NAME: "collectd"
    restart: always

volumes:
  grafana:
  postgres:
